services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=usersdb
      - DB_PORT=5432
      - HTTP_PORT=8080
      - GRPC_PORT=9090
      - GIN_PORT=8000

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=usersdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
